# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20171129_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.User'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Platform'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='release_date',
            field=models.DateField(blank=True, verbose_name='Release date'),
        ),
    ]
