# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.URLField(null=True),
        ),
    ]
